name: Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Build and publish
        run: |
          ./scripts/build_and_publish.sh ${{ secrets.PYPI_PASSWORD }}
        env:
          CI: 1
